ingress:
  enabled: true
  hosts:
    - telegram-app.example.com
  annotations:
    #cert-manager.io/cluster-issuer: "letsencrypt-prod"
    kubernetes.io/ingress.class: nginx
    #kubernetes.io/tls-acme: "true"
  tls:
#  tls:
#    - secretName: telegram-tls
#      hosts:
#       - chart-example.local

service:
  env:
    DEBUG: true
    FLASK_APP: app/main.py
    SESSION_DYNAMODB_TABLE: Sessions
    SESSION_DYNAMODB_REGION: eu-west-1
    SESSION_COOKIE_HTTPONLY: false